### ISSUE TITLE
quote escape echo commands

### ISSUE THREAD

**Issue by johnjaylward** [jedediahfrey/FreeNAS-Gogs#4]
in the root shell script, you have 3 commands:

``` bash
echo memcached_enable="YES" >> /etc/rc.conf
echo redis_enable="YES" >> /etc/rc.conf
...
echo gogs_enable="YES" >> /etc/rc.conf
```

it looks like you want to output the exact string `memcached_enable="YES"` to the rc.conf file, but instead what it output is `memcached_enable=YES`

if you quote escape each echo command, the output will be correct:

``` bash
echo 'memcached_enable="YES"' >> /etc/rc.conf
echo 'redis_enable="YES"' >> /etc/rc.conf
...
echo 'gogs_enable="YES"' >> /etc/rc.conf
```

**Comment by jedediahfrey** [comment]
Changed all of those lines to use ``sysrc``.
