### ISSUE TITLE
SSL certificate problem

### ISSUE THREAD

**Issue by francis-io** [jedediahfrey/FreeNAS-Gogs#7]
On a fresh jail on FreeNAS-9.3-STABLE-201605170422 I get the following error:

```
root@git-server:/home/user1/FreeNAS-Gogs


Fetching gogs from Github
# cd .; git clone https://go.googlesource.com/text /usr/home/git/go/src/golang.org/x/text
Cloning into '/usr/home/git/go/src/golang.org/x/text'...
fatal: unable to access 'https://go.googlesource.com/text/': SSL certificate problem: unable to get local issuer certificate
package golang.org/x/text/language: exit status 128
```

Googling the error, I found this[1] but it does not seem to make a difference.

[1] http://stackoverflow.com/a/34049063

**Comment by t3hG04T** [comment]
I ran into the same exact problem: for me solution was downgrading to lower version of ca_root_nss (namely 3.26 did the trick).

Apparently google servers are not up to snuff with the recent updates as I understand.

```sh
# cd to cache folder with older versions.
cd /var/cache/pkg
# Install previous version of the package.
pkg install ca_root_nss-3.26.txz
```

Mind you that might not be the last problem: later on I ran into some compiling problems (looks like the gcc version on freebsd is too old to compile smoothly and required some tiny source code editing).

**Comment by francis-io** [comment]
I don't have that package available, do I need to add any additional repos? (I don't have much experience with the way FreeBSD works).

```
root@git-server:/var/cache/pkg # pkg install ca_root_nss-3.26.txz
Updating FreeBSD repository catalogue...
FreeBSD repository is up-to-date.
All repositories are up-to-date.
Updating database digests format: 100%
pkg: No packages available to install matching 'ca_root_nss-3.26.txz' have been found in the repositories

root@git-server:/var/cache/pkg # pkg search ca_root_nss
ca_root_nss-3.27.1             Root certificate bundle from the Mozilla Project
```

**Comment by t3hG04T** [comment]
1. List the files in /var/cache/pkg (maybe you have an even older version here :)).
2. Before running the pkg install <specific version here> from this folder you might have to run pkg delete ca_root_nss to remove the newer version first (someone correct me if I'm wrong :)).

If this fails this is purely new territory for me, looks like https://www.freshports.org/ports-mgmt/portdowngrade might be the help we are looking for :)

**Comment by francis-io** [comment]
```
root@git-server:/var/cache/pkg # ls | grep nss
ca_root_nss-3.18-70a39f0c6f.txz
ca_root_nss-3.18.txz
ca_root_nss-3.27.1-8f8450e2ba.txz
ca_root_nss-3.27.1.txz
```

You were right, I had an older version I could install (without having to uninstall the currant. 

I then reran the install script and it seems to have worked, with some permission denied errors. I'm unsure why this could be since im running as root.

```
root@git-server:/home/user1/FreeNAS-Gogs # ./gogs-root.sh 
FreeNAS Gogs installation script.
This has been tested on:
    9.3-RELEASE-p29


Press any key to begin

Updating Gogs...

GOGS PID File not found. Maybe GOGS is not running?
Fetching gogs from Github
Getting gogs compile tags
Compiling gogs
Copying gogs build to git home
cp: /home/git/gogs/.git/objects/pack/pack-257d54bf5db8f30ab534ad6f89c0f762c1f732e7.idx: Permission denied
cp: /home/git/gogs/.git/objects/pack/pack-257d54bf5db8f30ab534ad6f89c0f762c1f732e7.pack: Permission denied
Copying startup script to rc.d, enabling & starting gogs
Update Done!

```

But I think you have solved my initial issue, thank you.

**Comment by jedediahfrey** [comment]
What where did you get the script that you're running where you're getting that error?

The line:

    cd .; git clone https://go.googlesource.com/text /usr/home/git/go/src/golang.org/x/text

Doesn't appear anywhere in the current master.

    freenas2# cd /mnt/basin/jails/gogs_10/tmp/FreeNAS-Gogs/
    freenas2# ls
.git		LICENSE		README.md	gogs-compile.sh	gogs-root.sh
    freenas2# grep googlesource *
    freenas2# 

The current master doesn't pull from googlesource but from github:

https://github.com/jedediahfrey/FreeNAS-Gogs/blob/master/gogs-compile.sh

Lines 3-4:

    echo "Fetching gogs from Github"
    su - git -c "setenv GOPATH /usr/home/git/go; go get -u github.com/gogits/gogs"

I just ran the current master on a new jail and it completed start to finish without any errors.

**Comment by francis-io** [comment]
I'm not in a position to look into this more on my box, but your right, I can't see anything relating to google in the code.

Anyway, installing an older ca_root_nss fixed this problem for me and Gogs seems to be working last time I left it, thank you both. This issue can be considered closed.

**Comment by t3hG04T** [comment]
Regarding google sources: is it possible that some packages are pulling dependencies from google code? There is quite a few of them; I was using the current gogs-compile version a few weeks back when encountering the same problem.

@jedediahfrey : have you run "pkg upgrade" on that jail before running your script? Default version of ca_root_nss is a bit older in the default jail, the problems start from version 3.27 (related to some sort of over-my-head security fix that google servers are not compatible with apparently).

Other than that: glad you got your gogs running, @francis-io . :)
